version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper_flink
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - flink-kafka-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 5s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka_flink
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9093:9093"  # internal broker listener
      - "29093:29093"  # host-accessible listener for Spring Boot
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - flink-kafka-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9093"]
      interval: 10s
      retries: 10

  flink-jobmanager:
    image: flink:1.18.0-java17
    container_name: flink-jobmanager_new
    ports:
      - "8082:8081" #flink UI
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    volumes:
      - ./build/libs:/opt/flink-jobs

    command: jobmanager
    networks:
      - flink-kafka-net

  flink-taskmanager:
    image: flink:1.18.0-java17
    container_name: flink-taskmanager_new
    ports:
      - "9251:9251" #metrics
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

    command: taskmanager
    networks:
      - flink-kafka-net


networks:
  flink-kafka-net:
    driver: bridge