server:
  port: 8088


spring:
  kafka:
    bootstrap-servers: localhost:29093  # ‚Üê Changed from 29093 to 9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: com.swift.flink_app.dto

app:
  kafka:
    topic: remittance-stream

  task:
    scheduling:
      pool:
        size: 2